"""Build the current rosoku core documentation from local source."""
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
import rosoku

project = 'Rosoku'
author = 'Simon Kojima, Alex Pepi'
copyright = '2026, Rosoku contributors'
version = release = rosoku.__version__
extensions = ['sphinx.ext.autodoc', 'sphinx.ext.napoleon', 'sphinx.ext.viewcode']
# Old autogenerated sources are retained on disk but do not describe this API.
exclude_patterns = ['auto_examples/**', 'rosoku.*.rst', 'sg_execution_times.rst']
source_suffix = {'.rst': 'restructuredtext'}
napoleon_numpy_docstring = True
napoleon_google_docstring = False
napoleon_use_param = True
napoleon_use_rtype = True
autodoc_typehints = 'description'
autodoc_member_order = 'bysource'
html_theme = 'pydata_sphinx_theme'
html_static_path = ['_static']
html_theme_options = {
    'logo': {'image_light': 'logo-light.png', 'image_dark': 'logo-dark.png'},
    'navbar_end': ['theme-switcher'],
}
html_title = f'Rosoku {release} documentation'
html_show_sourcelink = True
